#!/bin/bash

read -p "Digite a URL que deseja analisar: " url

curl -s "$url" | sed -n 's/.*<a href="\([^"]*\)".*/\1/p' | while read link; do
    subdomain=$(echo "$link" | sed -n 's/https\?:\/\/\([^\/]*\).*/\1/p')
    ip=$(host "$subdomain" | sed -n 's/.*has address \([^ ]*\).*/\1/p')
    echo "Link: $link IP: $ip"
done
