#!/bin/bash

read -p "Digite a URL que deseja analisar: " url

links=$(curl -sL "$url" |grep -Eo "https?:\/\/([^\/]*)" | sort -u)
for link in $links; do
i=$(echo $link | sed -E "s/https?:\/\///g")
echo "$link ($(dig +short $i | head -n1))"
done 


